# Generated by Django 3.1.2 on 2021-03-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='memo_approved',
        ),
        migrations.RemoveField(
            model_name='expenditure',
            name='pv_approved',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='remarks',
            field=models.CharField(max_length=1000, null=True, verbose_name='Memo Approved'),
        ),
    ]
