# Generated by Django 3.1.2 on 2021-03-02 21:54

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210302_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='remarks',
            field=models.CharField(max_length=1000, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Remarks'),
        ),
    ]
