# Generated by Django 3.1.2 on 2021-03-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210302_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Remarks'),
        ),
    ]
