# Generated by Django 3.1.7 on 2021-03-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210303_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='expenditure',
            name='remarks',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='remarks',
            field=models.ManyToManyField(to='app.Observations', verbose_name='Remarks'),
        ),
    ]
