# Generated by Django 3.1.7 on 2021-03-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210304_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='remarks',
            field=models.ManyToManyField(related_name='expense', to='app.Observations', verbose_name='Remarks'),
        ),
    ]
