# Generated by Django 3.1.7 on 2021-03-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210304_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='remarks',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Remarks'),
        ),
        migrations.DeleteModel(
            name='Observations',
        ),
    ]
