# Generated by Django 3.1.7 on 2021-03-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210304_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_name', models.CharField(max_length=1000, verbose_name='Observation')),
            ],
        ),
        migrations.RemoveField(
            model_name='expenditure',
            name='remarks',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='remarks',
            field=models.ManyToManyField(to='app.Observation', verbose_name='Remarks'),
        ),
    ]
