# Generated by Django 3.1.7 on 2021-03-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210305_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='remarks',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Remarks'),
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
    ]
